[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"

[dependencies]
anyhow = "1.0.100"  # error handling
bytes = "1.10.1"  # helps manage buffers
bytes-utils = "0.1.4"
futures = "0.3.31"
memchr = "2.7.5"
thiserror = "2.0.16"  # error handling
tokio = { version = "1.47.1", features = ["full"] }  # async networking
tokio-util = { version = "0.7.16", features = ["codec"] }
