[package]
name = "tinikeyval-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { workspace = true }
memchr = "2.7"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
